# Build Angular

FROM node:18 As build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --prod


# serve with Nginx

FROM nginx:alpine


RUN rm -rf /usr/share/nginx/html/*

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/*  /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;" ]
